services:
  postgres:
    image: postgres:16
    container_name: nutria_db
    environment:
      POSTGRES_DB: nutria_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    ports:
      - '55432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: nutria_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - '8082:80'
    depends_on:
      - postgres
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: nutria_azurite
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - azurite_data:/data
    command: azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0

volumes:
  pgdata:
  azurite_data:
