--
-- PostgreSQL database dump
--

\restrict 9Lq0HzjwywlmicQqVTAInrT3tptQ8hJMqr9sLhP9ttu1c3MxgIE5qN9kQq92OYF

-- Dumped from database version 16.13 (Debian 16.13-1.pgdg13+1)
-- Dumped by pg_dump version 16.13 (Debian 16.13-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: medical_reports; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.medical_reports (
    id bigint NOT NULL,
    active boolean NOT NULL,
    created_at date NOT NULL,
    date date NOT NULL,
    document_url character varying(255) NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.medical_reports OWNER TO postgres;

--
-- Name: medical_reports_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.medical_reports ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.medical_reports_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: refresh_tokens; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.refresh_tokens (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL,
    revoked boolean NOT NULL,
    token character varying(100) NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.refresh_tokens OWNER TO postgres;

--
-- Name: refresh_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.refresh_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refresh_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    active boolean NOT NULL,
    birth_date date NOT NULL,
    created_at date NOT NULL,
    email character varying(255) NOT NULL,
    gender character varying(255) NOT NULL,
    last_names character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    updated_at date,
    CONSTRAINT users_gender_check CHECK (((gender)::text = ANY ((ARRAY['H'::character varying, 'M'::character varying, 'NE'::character varying])::text[]))),
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'YOUNGER'::character varying, 'FAMILY'::character varying])::text[])))
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: medical_reports; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.medical_reports (id, active, created_at, date, document_url, user_id) FROM stdin;
1	t	2026-05-13	2026-05-13	http://127.0.0.1:10000/devstoreaccount1/imagenes-nutria/user-1%2F5c55adf7-a0b0-4dfc-bd1a-f57909bd475e-Gu%C3%ADa%20Normas%20APA%20S%C3%A9ptima%207.%C2%AA%20Edici%C3%B3n%202020.pdf	1
2	t	2026-05-13	2026-05-13	http://127.0.0.1:10000/devstoreaccount1/imagenes-nutria/user-1%2F24a75722-2268-4811-b4c6-d2b33eb31057-Gu%C3%ADa%20Normas%20APA%20S%C3%A9ptima%207.%C2%AA%20Edici%C3%B3n%202020.pdf	1
\.


--
-- Data for Name: refresh_tokens; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.refresh_tokens (id, created_at, expires_at, revoked, token, user_id) FROM stdin;
1	2026-05-13 01:26:09.173189	2026-05-20 01:26:09.173156	f	b97dd0cf-842f-414c-9dfc-ca876e4b1b8c	1
2	2026-05-13 01:44:07.096286	2026-05-20 01:44:07.096259	f	3295acf6-a425-431d-a6a9-df2cd0f2412b	1
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, active, birth_date, created_at, email, gender, last_names, name, password, role, updated_at) FROM stdin;
1	t	2006-01-28	2026-05-13	admin@nutria.edu.pe	H	admin	admin	$2a$10$abtKTYZEG0PCc0OB9PEUE.7YNlE2zvqWqmoUs32LmwVOvG9IZKo1q	ADMIN	\N
\.


--
-- Name: medical_reports_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.medical_reports_id_seq', 2, true);


--
-- Name: refresh_tokens_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.refresh_tokens_id_seq', 2, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 1, true);


--
-- Name: medical_reports medical_reports_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.medical_reports
    ADD CONSTRAINT medical_reports_pkey PRIMARY KEY (id);


--
-- Name: refresh_tokens refresh_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: refresh_tokens ukghpmfn23vmxfu3spu3lfg4r2d; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT ukghpmfn23vmxfu3spu3lfg4r2d UNIQUE (token);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: refresh_tokens fk1lih5y2npsf8u5o3vhdb9y0os; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT fk1lih5y2npsf8u5o3vhdb9y0os FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: medical_reports fkifvv54pg0gleb3tsrkpnqok1m; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.medical_reports
    ADD CONSTRAINT fkifvv54pg0gleb3tsrkpnqok1m FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--

\unrestrict 9Lq0HzjwywlmicQqVTAInrT3tptQ8hJMqr9sLhP9ttu1c3MxgIE5qN9kQq92OYF

